version: '3.8'

services:
  database:
    container_name: nest-db
    hostname: nest-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/database
    command: tail -f /dev/null
